- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- name: Set SELinux state to disabled
  selinux:
    policy: targeted
    state: disabled
  ignore_errors: true

- name: Determine whether the port is listening
  shell: netstat -npl |grep "{{ os_info['use_port'] }}" |grep LISTEN
  ignore_errors: true
  register: rulest

- name: if port is listening then ansible exited
  fail: 
    msg: "port {{ os_info['use_port'] }}  has been listening, please check"
  when: rulest.rc == 0